# 服务配置
server:
  port: 9290
  servlet:
    context-path: /cwwj

spring:
  # 应用名称
  application:
    name: xd-cwwj
  # DataSource 配置
  datasource:
    driver-class-name: 自己填写
    url: 自己填写
    username: 自己填写
    password: 自己填写

# MyBatis 配置
mybatis:
  mapper-locations: classpath:static/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: on
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 提交信息配置
submit:
  sfzx: 1
  tw: 1
  area: 陕西省 西安市 长安区
  city: 西安市
  province: 陕西省
  address: 陕西省西安市长安区兴隆街道210国道
  geo_api_info: '{"type":"complete","position":{"Q":34.126833224827,"R":108.84419433593803,"lng":108.844194,"lat":34.126833},"location_type":"html5","message":"Get ipLocation failed.Get geolocation success.Convert Success.Get address success.","accuracy":74,"isConverted":true,"status":1,"addressComponent":{"citycode":"029","adcode":"610116","businessAreas":[],"neighborhoodType":"","neighborhood":"","building":"","buildingType":"","street":"雷甘路","streetNumber":"230号","country":"中国","province":"陕西省","city":"西安市","district":"长安区","township":"兴隆街道"},"formattedAddress":"陕西省西安市长安区兴隆街道210国道","roads":[],"crosses":[],"pois":[],"info":"SUCCESS"}'
  sfcyglq: 0
  sfyzz: 0
  qtqk: ""
  ymtys: 0

# 邮件通知配置
mail:
  host: smtp.qq.com
  sender: 自己填写
  password: 自己填写
  subject: 晨午晚检上报通知
  content: 您已成功上报
